### ISSUE TITLE
loading weights issue

### ISSUE THREAD

**Issue by JoeHEZHAO** [sunshineatnoon/Darknet.keras#5]
Hi, I have downloaded yolo-tiny.weights  and put it into folder 'weights'. 

Then happens an ERROR:
Using Theano backend.
Traceback (most recent call last):
  File "RunTinyYOLO.py", line 194, in <module>
    yoloNet = ReadTinyYOLONetWeights(os.path.join(os.getcwd(),'weights/yolo-tiny.weights'))
  File "D:\DeepLearningProgram\Darknet.keras-master\utils\TinyYoloNet.py", line 80, in ReadTinyYOLONetWeights
    l.biases = np.asarray(testArray[0][count])
IndexError: index 0 is out of bounds for axis 0 with size 0

And I check file 'TinyYoloNet.py', def 'ReadTinyYOLONetWeights', the 'testArray' variable is [] (null) with many many dtype.

What is the problem ??

**Comment by yongwoncho** [comment]
I have this problem. Did yo solve this problem?

**Comment by Walid-Ahmed** [comment]
I have the same problem

**Comment by sunshineatnoon** [comment]
this code is written for older version of YOLO weight, now the weight has updated to version 2.0, so the code is no longer working.

**Comment by Walid-Ahmed** [comment]
Thanks

any chance you will update the code ?

Walid

**Comment by sunshineatnoon** [comment]
@Walid-Ahmed I'm sorry but I am too busy recently, and reading weights bite by bite is a nasty job. If you need a off the shelf object detection algorithm that is implemented in popular framework, I recommend [SSD](https://github.com/weiliu89/caffe/tree/ssd), it's implemented in caffe and has a [re-implement version](https://github.com/zhreshold/mxnet-ssd) in MXNET.

**Comment by JoshGlue** [comment]
This is an old issue, but you can download the old weights at: http://pjreddie.com/media/files/yolo-tiny.weights . For me the code works when I load that weights-file.

**Comment by sunshineatnoon** [comment]
@JoshGlue Thanks, I've been looking for this weight for a long time.
