### ISSUE TITLE
Exception when trying to run code

### ISSUE THREAD

**Issue by Walid-Ahmed** [sunshineatnoon/Darknet.keras#7]
I followed the instructions but I can not run code
I got the following 
line 80, in ReadTinyYOLONetWeights
    l.biases = np.asarray(testArray[0][count])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by sunshineatnoon** [comment]
Sorry, this code is written for older version of YOLO weight, now the weight has updated to version 2.0, so the code is no longer working.
